const ExercisesList: Record<string, string[]> = {
  Shoulders: [
    "Arnold Dumbbell Press",
    "Barbell Front Raises",
    "Behind The Neck Barbell Press",
    "Cable Face Pull",
    "Front Dumbbell Raise",
    "Hammer Strength Shoulder Press",
    "Incline Rear Delt Dumbbell Row",
    "Lateral Dumbbell Raise",
    "Lateral Machine Raise",
    "Low-Pulley Bent-over Lateral Raises",
    "Low-Pulley Standing Lateral Raises",
    "Military Press",
    "One-Arm Standing Dumbbell Press",
    "Overhead Press",
    "Push Press",
    "Rear Delt Dumbbell Raise",
    "Rear Delt Machine Fly",
    "Seated Barbell Press",
    "Seated Barbell Press Smith Machine",
    "Seated Dumbbell Lateral Raise",
    "Seated Dumbbell Press",
    "Smith Machine Overhead Press",
    "Upright Row",
  ],
  Triceps: [
    "Cable Overhead Triceps Extension",
    "Close Grip Barbell Bench Press",
    "Dumbbell Overhead Triceps Extension",
    "Dumbell Kickback",
    "EZ-Bar Skullcrusher",
    "Lying Triceps Extension",
    "Narrow Push-ups",
    "One Arm Reverse Pushdown",
    "Parallel Bar Triceps Dip",
    "Ring Dip",
    "Rope Push Down",
    "Smith Machine Close Grip Bench Press",
    "V-Bar Push Down",
  ],
  Biceps: [
    "Barbell Curl",
    "Barbell Curl Against Incline",
    "Cable Curl",
    "Dumbbell Concentration Curl",
    "Dumbbel Curl",
    "Dumbbell Hammer Curl",
    "Dumbbell Preacher Curl",
    "EZ-Bar Curl",
    "EZ-Bar Preacher Curl",
    "Machine Preacher Curl",
    "Seated Dumbbell Curl",
    "Seated Incline Dumbbell Curl",
    "Seated Machine Curl",
  ],
  Chest: [
    "Cable Crossover",
    "Decline Barbell Bench Press",
    "Decline Hammer Strength Chest Press",
    "Flat Barbell Bench Press",
    "Flat Dumbbell Bench Press",
    "Flat Dumbbell Fly",
    "Incline Barbell Bench Press",
    "Incline Dumbbell Bench Press",
    "Incline Dumbbell Fly",
    "Incline Hammer Strength Chest Press",
    "Parallel Bar Dips",
    "Pectoral Fly",
    "Push-ups",
    "Seated Machine Fly",
  ],
  Back: [
    "Barbell Row",
    "Barbell Shrug",
    "Chin Up",
    "Deadlift",
    "Dual Pulley Seated Cable Row",
    "Dumbbell Row",
    "Good Morning",
    "Hammer Strength Row",
    "Hyperextension",
    "Lat Pulldown",
    "Machine Shrug",
    "Neutral Chin Up",
    "Pendlay Row",
    "Pull Up",
    "Rack Pull",
    "Seated Cable Row",
    "Seated Row Machine",
    "Straight-Arm Cable Pushdown",
    "T-Bar Row",
  ],
  Legs: [
    "Barbell Calf Raise",
    "Barbell Front Squat",
    "Barbell Glute Bridge",
    "Barbell Squat",
    "Barbell Squat Smith Machine",
    "Donkey Calf Raise",
    "Glute Machine",
    "Glute-Ham Raise",
    "Leg Extension Machine",
    "Leg Press",
    "Lying Leg Curl Machine",
    "Romanian Deadlift",
    "Seated Calf Raise Machine",
    "Seated Leg Curl Machine",
    "Standing Calf Raise Machine",
    "Standing Glute Extension Machine",
    "Stiff-Legged Deadlift",
    "Sumo Deadlift",
    "Walking Lunges",
  ],
  Abs: [
    "Ab-Wheel Rollout",
    "Butt Ups",
    "Cable Crunch",
    "Crunch",
    "Crunch Machine",
    "Decline Crunch",
    "Dragon Flag",
    "Hanging Knee Raise",
    "Hanging Leg Raise",
    "Plank",
    "Side Dumbbell/Weight Bend",
    "Side Plank",
    "Standings Side Dumbbell",
  ],
};

export default ExercisesList;
